version: '3'

services:

  app:
    build:
      context: ./app
    networks:
      - net

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/cert/:/cert
    networks:
      - net
 
networks:
  net:
